### ISSUE TITLE
Schema 

### ISSUE THREAD

**Issue by macrobian88** [ashiqsultan/twilio-whatsapp-ai-bot#1]
Hi,

Can you please drop the sample schema which you are using for different collections like Doctor, Patient etc.

Also, I would be really great if you add the sample json which you receive from twilio web hook.

**Comment by ashiqsultan** [comment]
> Hi,
> 
> Can you please drop the sample schema which you are using for different collections like Doctor, Patient etc.
> 
> Also, I would be really great if you add the sample json which you receive from twilio web hook.

Hi, you can refer this for the req body you will receive for WhatsApp msgs from Twilio
https://www.twilio.com/docs/messaging/guides/webhook-request#request-parameters

As for schema its a vague one as its a hackathon project but anyways since you asked for
# Patient
{
   "_id": Mongo db default coll id
   "phone_no":"919999999999",
   "easyId":"e613pa",
   "prefLang":"english",
   "details":{
      "name":"John",
      "age":"25",
      "gender":"male",
// Any other stuff
   }
}
# Consultation
{
    "_id":
    "phone_no":"", // foreign key for patients 
    "summary":""
 }
# Doctor
{id,
name,
description:"Speciality and stuff",
phoneNo:""
}
